---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Configure Nginx
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
    mode: '0644'
  notify: 
    - Restart Nginx

- meta: flush_handlers

- name: Ensure Nginx is running and enabled on startup
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Install Prometheus Nginx Exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter
    state: present

- name: Ensure Prometheus Nginx Exporter is running and enabled on startup
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: started
    enabled: true
