- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Copy default.j2 
  ansible.builtin.template:
    src: default.j2 
    dest: /etc/nginx/sites-enabled/default
  notify:
    - Restart Nginx

- name: ngnix service start
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true