- name: Install Nginx and exporter
  ansible.builtin.apt:
    name: 
      - nginx
      - prometheus-nginx-exporter
    state: present


- name: copy nginx config
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
    mode: '0644'
  notify: 
    - Restart Nginx
    - Restart nginx exporter


- name: nginx and exporter service  start
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - nginx
    - prometheus-nginx-exporter