- name: Install HAProxy
  apt:
    name: haproxy

- name: Add haproxy configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart haproxy

- name: Start HAProxy
  service:
    name: haproxy
    state: started
    enabled: true


# prometheus haproxy exporter

- name: Install prometheus-haproxy-exporter
  apt:
    name: prometheus-haproxy-exporter

- name: Start prometheus-haproxy-exporter
  service:
    name: prometheus-haproxy-exporter
    state: started
    enabled: true 

- name: Configure prometheus-haproxy-exporter
  template:
    dest: /etc/default/prometheus-haproxy-exporter
    src: prometheus-haproxy-exporter
  notify: Restart prometheus-haproxy-exporter



# add cnames for haproxy
- name: add cnames
  include_role:
    name: "cname"
  vars:
    service: "lb{{inventory_hostname | replace('akhkusu','')}}"