---

- name: Create volume directories
  ansible.builtin.file:
    path: /opt/grafana/provisioning/{{ item }}
    state: directory
  loop:
    - dashboards
    - datasources

- name: Copy grafana configs to volume
  template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  notify: Restart grafana
  no_log: true

- name: Copy dashboards config to volume
  template:
    src: dashboards.yaml.j2
    dest: /opt/grafana/provisioning/dashboards/dashboards.yaml
  notify: Restart grafana

- name: Copy datasources config to volume
  template:
    src: datasources.yaml.j2
    dest: /opt/grafana/provisioning/datasources/datasources.yaml
  notify: Restart grafana

- name: Copy all dashboards to volume
  copy:
    src: "{{ item }}"
    dest: /opt/grafana/provisioning/dashboards/{{ item }}
  loop:
    - main.json
    - mysql.json
    - syslog.json
    - backups.json
  notify: Restart grafana



- name: Install Grafana via Docker
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana
    volumes: /opt/grafana:/etc/grafana
    restart_policy: always
    published_ports: "{{ grafana_port }}:3000"
  


- name: run grafana handlers
  meta: flush_handlers

- name: Make sure grafana is running
  community.docker.docker_container:
    image: grafana/grafana
    name: grafana
    state: started


# add cnames
- name: add cnames
  include_role:
    name: "cname"
  vars:
    service: "grafana"
    