---

- name: Install Grafana via Docker
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana
    volumes: /opt/grafana:/etc/grafana
    published_ports: "{{ grafana_port }}:3000"

- name: Create volume directories
  ansible.builtin.file:
    path: /opt/grafana/provisioning/{{ item }}
    state: directory
  loop:
    - dashboards
    - datasources

- name: Copy grafana configs to volume
  template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  notify: Restart grafana
  no_log: true

- name: Copy dashboards config to volume
  template:
    src: dashboards.yaml.j2
    dest: /opt/grafana/provisioning/dashboards/dashboards.yaml
  notify: Restart grafana

- name: Copy datasources config to volume
  template:
    src: datasources.yaml.j2
    dest: /opt/grafana/provisioning/datasources/datasources.yaml
  notify: Restart grafana

- name: Copy all dashboards to volume
  copy:
    src: "{{ item }}"
    dest: /opt/grafana/provisioning/dashboards/{{ item }}
  loop:
    - main.json
    - mysql.json
    - syslog.json
    - backups.json
  notify: Restart grafana

# - name: Add grafana A record
#   include_role:
#     name: dns_record
#     tasks_from: add_dns_records
#   vars:
#     record: "grafana"
#     value: "{{ groups['grafana_servers'][0] }}"
#     type: "CNAME"