---
- name: install dependencies
  ansible.builtin.apt:
    name: uwsgi
    state: present

- name: install dependencies
  ansible.builtin.apt:
    name: uwsgi-plugin-python3
    state: present      

- name: copy uwsgi config
  ansible.builtin.template:
    dest: /etc/uwsgi/apps-enabled/agama.ini
    src: ../templates/agama.ini.j2
    owner: agama
    mode: 0600
  no_log: true  
  notify: Restart uWSGI


- name: uWSGI service
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: true

    