{
 "title": "Backup",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Last Backup Success  InfluxDB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - backup_last_success_time{user=\"akhkusu\", service=\"influxdb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Backup Success MySQL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - backup_last_success_time{user=\"akhkusu\", service=\"mysql\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Backups",
   "type": "stat",
   "gridPos": { "h": 4, "w": 14, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backups_total{user=\"akhkusu\"}",
     "legendFormat": "{{service}} {{type}}"
    }
   ]
  }
 ]
}