{
 "title": "Main",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Keepalived Vrrp state",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "keepalived_vrrp_state", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CPU load (0% - 100%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg(1 - rate(node_cpu_seconds_total{mode=\"idle\"}[30m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Items for all discovered Agamas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"items\") FROM \"autogen\".\"agama-stats\" WHERE $timeFilter GROUP BY time(5m) fill(null)\n"
    }
   ]
  },
  {
   "title": "Items in my Agama",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT LAST(\"items\") AS \"last_items\" \nFROM \"agama-stats\" \nWHERE \"name\" =~ /akhkusu-(1|2)\\.ak\\.io\\./\n"
    }
   ]
  },
  {
   "title": "Bind UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "MySQL Queries",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 4 },
   "targets": [
    {
     "expr": "sum by (instance)(\n    rate(\n        mysql_global_status_commands_total[2m]\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Load ( 0% - 100% )",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes[30m]) + avg_over_time(node_memory_Cached_bytes[30m]) + avg_over_time(node_memory_Buffers_bytes[30m])) / avg_over_time(node_memory_MemTotal_bytes[30m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MySQL UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "InfluxDb Write Ok",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "\nrate (\n    influxdb_write_write_ok[2m]\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "InfluxDB Query Success",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 8 },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Nginx UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "HAproxy UP",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "HAproxy 2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"lb-2:9101\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bind Queries Total",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 14 },
   "targets": [
    {
     "expr": "sum by (instance) (\n    rate(bind_incoming_requests_total[2m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx http requests total",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 14 },
   "targets": [
    {
     "expr": "sum by (instance) (\n    rate(nginx_http_requests_total[2m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HAproxy 1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"lb-1:9101\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}