{
 "title": "MySQL Health",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "MySQL Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MySQL id",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL Server Mode",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SQL Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running{master_uuid!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "I/O Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running{master_uuid!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}