---
- name: Restart bind9
  ansible.builtin.service:
    name: bind9
    state: restarted


- name: RNDC Reload
  command: rndc reload


- name: Reload systemd daemon
  ansible.builtin.command: systemctl daemon-reload