- name: create user agama
  ansible.builtin.user:
    user: agama
    state: present

- name: create directory
  ansible.builtin.file:
    owner: agama
    state: directory
    path: /opt/agama

- name: install dependencies
  ansible.builtin.apt:
    name: python3-flask-sqlalchemy
    state: present

- name: install agama
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama