- name: add cnames records
  community.general.nsupdate:
    key_algorithm: "hmac-sha256"
    key_name: "nsupdate.key"
    key_secret: "{{ dns_nsupdate_secret }}"
    record: "{{ service }}"
    server: "{{hostvars[groups['dns_primary'][0]]['ansible_default_ipv4']['address']}}"
    state: present
    type: CNAME
    zone: "{{ domain_name }}"
    value: "{{ inventory_hostname }}"
  no_log: true