- name: Restart influxdb
  service:
    name: influxdb
    state: restarted

- name: Restart telegraf
  service:
    name: telegraf
    state: restarted

- name: Restart systemctl daemon
  systemd:
   daemon_reload: true