---
- name: Install Prometheus
  ansible.builtin.apt:
    name: prometheus
    state: present

- name: Modify /etc/prometheus/prometheus.yml
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify:
    - Restart Prometheus

- name: Copy Prometheus default file
  ansible.builtin.template:
    src: prometheus_default.j2
    dest: /etc/default/prometheus
  notify:
    - Restart Prometheus


- name: Enable Prometheus
  service:
    name: prometheus 
    state: started
    enabled: yes




- name: add cnames
  include_role:
    name: "cname"
  vars:
    service: "prometheus"