---
- name: install bind9
  ansible.builtin.apt:
    name: bind9
    state: present


- name: copy conf.options
  ansible.builtin.template:
    dest: /etc/bind/named.conf.{{ item }}
    src: named.conf.{{ item }}.j2
  loop:
    - options
    - local
  notify: 
    - Restart bind9
    - RNDC Reload

- name: copy zone
  ansible.builtin.template:
    dest: /var/cache/bind/db.ak.io
    src: zone.j2 
    force: no
  notify: 
    - Restart bind9
    - RNDC Reload
  when: inventory_hostname in groups ['dns_primary']

- name: copy reverse zone
  ansible.builtin.template:
    dest: /var/cache/bind/rev.db.ak.io
    src: reverse.zone.conf.j2
    force: yes
  notify: 
    - Restart bind9
    - RNDC Reload
  when: inventory_hostname in groups ['dns_primary']
  


#Exporter 

- name: Download Bind9 Exporter archive
  ansible.builtin.get_url:
    url: https://github.com/prometheus-community/bind_exporter/releases/download/v0.6.1/bind_exporter-0.6.1.linux-amd64.tar.gz
    dest: /opt/bind_exporter-0.6.1.tar.gz
    mode: '0644'

- name: Extract Bind9 Exporter archive
  ansible.builtin.unarchive:
    src: /opt/bind_exporter-0.6.1.tar.gz
    dest: /opt/
    remote_src: yes

- name: Create symbolic link to exporter executable
  ansible.builtin.file:
    src: /opt/bind_exporter-0.6.1.linux-amd64/bind_exporter
    dest: /usr/local/bin/prometheus-bind-exporter
    state: link

- name: Create systemd service definition for Bind9 Exporter
  ansible.builtin.template:
    src: bind_exporter.service.j2
    dest: /etc/systemd/system/bind_exporter.service
    mode: '0644'
  notify: 
    - Reload systemd daemon


- name: Make sure bind9 and exporter are running
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - bind9
    - bind_exporter
    

- name: Run handlers
  meta: flush_handlers



- name: install dependency for nsupdate
  ansible.builtin.apt:
    name: python3-dnspython
    state: present




- name: Add A backup record on backup dns servers
  community.general.nsupdate:
    key_algorithm: hmac-sha256
    key_name: nsupdate.key
    key_secret: "{{ dns_nsupdate_secret }}"
    record: backup
    server: "{{hostvars[groups['dns_primary'][0]]['ansible_default_ipv4']['address']}}"
    state: present
    type: A
    zone: "{{ domain_name }}"
    value: "{{ backup_server_ip }}"
  when: inventory_hostname in groups['dns_primary']


- name: add cnames
  include_role:
    name: "cname"
  vars:
    service: "ns{{inventory_hostname | replace('akhkusu','')}}"
    