---
- name: install bind9
  ansible.builtin.apt:
    name: bind9
    state: present


- name: copy conf.options
  ansible.builtin.template:
    dest: /etc/bind/named.conf.{{ item }}
    src: named.conf.{{ item }}.j2
  loop:
    - options
    - local
  notify: 
    - Restart bind9
    - RNDC Reload

- name: copy zone
  ansible.builtin.template:
    dest: /var/cache/bind/db.ak.io
    src: zone.j2 
  notify: 
    - Restart bind9
    - RNDC Reload


#Exporter 

- name: Install prometheus-bind-exporter
  apt:
    name: prometheus-bind-exporter


- name: Make sure bind9 and exporter are running
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - bind9
    - prometheus-bind-exporter









    