---
- name: install bind9
  ansible.builtin.apt:
    name: bind9
    state: present


- name: copy conf.options
  ansible.builtin.template:
    dest: /etc/bind/named.conf.{{ item }}
    src: named.conf.{{ item }}.j2
  loop:
    - options
    - local
  notify: 
    - Restart bind9
    - RNDC Reload

- name: copy zone
  ansible.builtin.template:
    dest: /var/cache/bind/db.ak.io
    src: zone.j2 
  notify: 
    - Restart bind9
    - RNDC Reload


#Exporter 

- name: Download Bind9 Exporter archive
  ansible.builtin.get_url:
    url: https://github.com/prometheus-community/bind_exporter/releases/download/v0.6.1/bind_exporter-0.6.1.linux-amd64.tar.gz
    dest: /opt/bind_exporter-0.6.1.tar.gz
    mode: '0644'

- name: Extract Bind9 Exporter archive
  ansible.builtin.unarchive:
    src: /opt/bind_exporter-0.6.1.tar.gz
    dest: /opt/
    remote_src: yes

- name: Create symbolic link to exporter executable
  ansible.builtin.file:
    src: /opt/bind_exporter-0.6.1.linux-amd64/bind_exporter
    dest: /usr/local/bin/prometheus-bind-exporter
    state: link

- name: Create systemd service definition for Bind9 Exporter
  ansible.builtin.template:
    src: bind_exporter.service.j2
    dest: /etc/systemd/system/bind_exporter.service
    mode: '0644'
  notify: 
    - Reload systemd daemon


- name: Make sure bind9 and exporter are running
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - bind9
    - bind_exporter
    







    